channels:
  - conda-forge
  - defaults
dependencies:
  - streamlit=1.29.0=pyhd8ed1ab_0
  - pypdf2=2.11.1=pyhd8ed1ab_0
  - langchain=0.0.333=pyhd8ed1ab_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pip:
      - huggingface-hub==0.17.3
      - faiss-cpu==1.7.4
      - instructorembedding==1.0.1
      - python-dotenv==1.0.0
      - sentence-transformers==2.2.2
      - transformers==4.35.0